variables:
    DOCKER_DRIVER: overlay
    CI_REGISTRY_IMAGE_WITH_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    DOCKER_HUB_IMAGE_LATEST: "$DOCKER_HUB_IMAGE:latest"
    DOCKER_HUB_IMAGE_RELEASE: "$DOCKER_HUB_IMAGE:$DOCKER_HUB_RELEASE"

stages:
  - build
  - deploy

build:docker-image:
    image: docker:latest
    stage: build
    services:
      - docker:dind
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -t $CI_REGISTRY_IMAGE_WITH_TAG --no-cache=true .
      - docker push $CI_REGISTRY_IMAGE_WITH_TAG
    only:
      - master
    tags:
      - docker

deploy:docker-image:
    image: docker:latest
    stage: deploy
    services:
      - docker:dind
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - docker pull $CI_REGISTRY_IMAGE_WITH_TAG
      - docker tag $CI_REGISTRY_IMAGE_WITH_TAG $DOCKER_HUB_IMAGE_LATEST
      - docker push $DOCKER_HUB_IMAGE_LATEST
      - docker tag $CI_REGISTRY_IMAGE_WITH_TAG $DOCKER_HUB_IMAGE_RELEASE
      - docker push $DOCKER_HUB_IMAGE_RELEASE
    only:
      - master
    tags:
      - docker
